# Generated by Django 3.0 on 2021-09-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('names', models.CharField(max_length=10)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('qualification_debtor', models.CharField(choices=[('bueno', 'bueno'), ('regular', 'regular'), ('malo', 'malo')], max_length=10)),
                ('score', models.PositiveSmallIntegerField(help_text="reaffirms the decision of the supervising user by validating the client's profile, it is assigned by the system")),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
