# Generated by Django 3.0 on 2021-09-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('aprobado', 'aprobado'), ('denegado', 'denegado'), ('por evaluar', 'por evaluar')], default='por evaluar', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='qualification_debtor',
            field=models.CharField(choices=[('bueno', 'bueno'), ('regular', 'regular'), ('malo', 'malo')], max_length=7),
        ),
    ]
