# Generated by Django 3.0 on 2021-09-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20210923_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='names',
            field=models.CharField(max_length=30),
        ),
    ]
